name: kortobaa_task
description: A new Flutter project for Kortobaa LLC.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  # State Management
  provider: ^4.3.2+2
  state_notifier: ^0.6.0
  flutter_state_notifier: ^0.6.1
  rxdart: ^0.24.1
  equatable: ^1.2.0
  flutter_bloc: ^6.0.1
  bloc: ^6.0.1
  
  # UI and  Responsiveness
  device_preview: ^0.4.7
  fluttertoast: ^6.0.1
  image_picker: ^0.6.7+4
  extended_image: ^0.7.3+1
  flare_flutter: ^2.0.6
 

  # Localization 
  flutter_i18n: ^0.16.2

  # Firebase
  firebase_core: ^0.5.0
  cloud_firestore: ^0.14.0+1
  firebase_storage: ^4.0.0
  
  # Utilities
  device_info: ^0.4.2+6
  uuid: ^2.2.0
  intl: ^0.16.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/kortobaa.png"

flutter:
  uses-material-design: true

  ############## Assets ( Images / Fonts / Languages ) ##############

  assets:
    - assets/images/
    - assets/flutter_i18n/
    - assets/animations/

  fonts:
    - family: 'Poppins'
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf


    - family: 'Cairo'
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
